apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: canardier/cruise:api
        ports:
        - containerPort: 5000
      nodeName: worker-1
      volumes:
      - name: pv-myapi
        persistentVolumeClaim:
          claimName: api-volume