CREATE TABLE cruise
(
    id INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150)
);

/*script generated for free with OnlineDataGenerator available at: https://www.onlinedatagenerator.com */
INSERT INTO cruise(name) VALUES('Florida State University');
INSERT INTO cruise(name) VALUES('Rensselaer Polytechnic University');
INSERT INTO cruise(name) VALUES('Washington State University');
INSERT INTO cruise(name) VALUES('The Ohio State University');
INSERT INTO cruise(name) VALUES('University of Chicago');
INSERT INTO cruise(name) VALUES('Columbia University');
INSERT INTO cruise(name) VALUES('Columbia University');
INSERT INTO cruise(name) VALUES('Northeastern University');
INSERT INTO cruise(name) VALUES('University of Minnesota');
INSERT INTO cruise(name) VALUES('University of New Mexico');
INSERT INTO cruise(name) VALUES('Virginia Polytechnic Institute and State University');
INSERT INTO cruise(name) VALUES('University of Rochester');
INSERT INTO cruise(name) VALUES('Rice University');
INSERT INTO cruise(name) VALUES('University of South Florida');
INSERT INTO cruise(name) VALUES('University of Illinois, Chicago (UIC)');
INSERT INTO cruise(name) VALUES('Stanford University');
INSERT INTO cruise(name) VALUES('Stony Brook University, State University of New York');
INSERT INTO cruise(name) VALUES('Texas A&M University');
INSERT INTO cruise(name) VALUES('Brandeis University');
INSERT INTO cruise(name) VALUES('University of Chicago');
INSERT INTO cruise(name) VALUES('Harvard University');
INSERT INTO cruise(name) VALUES('Rice University');
INSERT INTO cruise(name) VALUES('University of Miami');
INSERT INTO cruise(name) VALUES('University of Miami');
INSERT INTO cruise(name) VALUES('University of Connecticut');
INSERT INTO cruise(name) VALUES('The New School');
INSERT INTO cruise(name) VALUES('Rice University');
INSERT INTO cruise(name) VALUES('Illinois Institute of Technology');
INSERT INTO cruise(name) VALUES('Georgia Institute of Technology');
INSERT INTO cruise(name) VALUES('Florida State University');
INSERT INTO cruise(name) VALUES('University of North Carolina, Chapel Hill');
INSERT INTO cruise(name) VALUES('University of Notre Dame');
INSERT INTO cruise(name) VALUES('The New School');
INSERT INTO cruise(name) VALUES('Yale University');
INSERT INTO cruise(name) VALUES('Princeton University');
INSERT INTO cruise(name) VALUES('Pennsylvania State University');
INSERT INTO cruise(name) VALUES('Yale University');
INSERT INTO cruise(name) VALUES('The University of Arizona');
INSERT INTO cruise(name) VALUES('The University of Georgia');
INSERT INTO cruise(name) VALUES('Brown University');
INSERT INTO cruise(name) VALUES('University of Maryland, Baltimore County');
INSERT INTO cruise(name) VALUES('The University of Georgia');
INSERT INTO cruise(name) VALUES('Washington University in St. Louis');
INSERT INTO cruise(name) VALUES('Washington State University');
INSERT INTO cruise(name) VALUES('The University of Arizona');
INSERT INTO cruise(name) VALUES('Howard University');
INSERT INTO cruise(name) VALUES('Tulane University');
INSERT INTO cruise(name) VALUES('North Carolina State University');
INSERT INTO cruise(name) VALUES('The University of Tennessee, Knoxville');
INSERT INTO cruise(name) VALUES('Rutgers University - New Brunswick');
INSERT INTO cruise(name) VALUES('Iowa State University');
INSERT INTO cruise(name) VALUES('University of Utah');
INSERT INTO cruise(name) VALUES('University of Southern California');
INSERT INTO cruise(name) VALUES('University of Colorado, Denver');
INSERT INTO cruise(name) VALUES('University of New Mexico');
INSERT INTO cruise(name) VALUES('University of Colorado Boulder');
INSERT INTO cruise(name) VALUES('University of Miami');
INSERT INTO cruise(name) VALUES('Northeastern University');
INSERT INTO cruise(name) VALUES('Michigan State University');
INSERT INTO cruise(name) VALUES('University of Maryland, College Park');
INSERT INTO cruise(name) VALUES('Princeton University');
INSERT INTO cruise(name) VALUES('University of Virginia');
INSERT INTO cruise(name) VALUES('Columbia University');
INSERT INTO cruise(name) VALUES('Drexel University');
INSERT INTO cruise(name) VALUES('University of California, Irvine');
INSERT INTO cruise(name) VALUES('Indiana University Bloomington');
INSERT INTO cruise(name) VALUES('Purdue University');
INSERT INTO cruise(name) VALUES('Tulane University');
INSERT INTO cruise(name) VALUES('Clark University');
INSERT INTO cruise(name) VALUES('University of Rochester');
INSERT INTO cruise(name) VALUES('The University of Georgia');
INSERT INTO cruise(name) VALUES('Duke University');
INSERT INTO cruise(name) VALUES('Rice University');
INSERT INTO cruise(name) VALUES('Colorado State University');
INSERT INTO cruise(name) VALUES('University of Virginia');
INSERT INTO cruise(name) VALUES('Howard University');
INSERT INTO cruise(name) VALUES('University of Maryland, Baltimore County');
INSERT INTO cruise(name) VALUES('The Ohio State University');
INSERT INTO cruise(name) VALUES('University of New Mexico');
INSERT INTO cruise(name) VALUES('Tufts University');
INSERT INTO cruise(name) VALUES('Princeton University');
INSERT INTO cruise(name) VALUES('University of California, Davis');
INSERT INTO cruise(name) VALUES('New York University');
INSERT INTO cruise(name) VALUES('Tufts University');
INSERT INTO cruise(name) VALUES('Purdue University');
INSERT INTO cruise(name) VALUES('University of Rochester');
INSERT INTO cruise(name) VALUES('Virginia Polytechnic Institute and State University');
INSERT INTO cruise(name) VALUES('University at Buffalo SUNY');
INSERT INTO cruise(name) VALUES('Arizona State University');
INSERT INTO cruise(name) VALUES('University of Delaware');
INSERT INTO cruise(name) VALUES('University of Colorado, Denver');
INSERT INTO cruise(name) VALUES('Clark University');
INSERT INTO cruise(name) VALUES('Arizona State University');
INSERT INTO cruise(name) VALUES('Princeton University');
INSERT INTO cruise(name) VALUES('University of Kansas');
INSERT INTO cruise(name) VALUES('Carnegie Mellon University');
INSERT INTO cruise(name) VALUES('University of Southern California');
INSERT INTO cruise(name) VALUES('University of Michigan');
INSERT INTO cruise(name) VALUES('Colorado State University');
INSERT INTO cruise(name) VALUES('Washington State University');
